project_id = "myuuhjoxkaygqxjueipm"

[functions.sync-amazon-shipments]
verify_jwt = true

[functions.amazon-oauth-exchange]
verify_jwt = true

[functions.analyze-invoice]
verify_jwt = true

[functions.send-missing-invoice-notification]
verify_jwt = true

[functions.get-amazon-client-id]
verify_jwt = false

[functions.get-google-client-id]
verify_jwt = false

[functions.gmail-oauth-exchange]
verify_jwt = true

[functions.sync-gmail-invoices]
verify_jwt = true
